name: flutter_banco_douro
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  envied: ^1.1.1
  flutter:
    sdk: flutter
  http: ^1.3.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  envied_generator: ^1.1.1
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - assets/images/
